name=NezaRTC
version=1.0.0
author=Emmanuel Mugwaneza
maintainer=Emmanuel Mugwaneza  <nezaemmy1@gmail.com>
sentence=Standalone RTC library for DS1307 and DS3231.
paragraph=No dependencies. Supports DS3231 alarms, 64-bit UNIX time, DS3231 century bit, DS1307 SRAM century storage.
category=Timing
url=https://github.com/Nezaemmy/NezaRTC
architectures=esp32, avr
includes=NezaRTC.h
